### ISSUE TITLE
recruit eddy

### ISSUE THREAD

**Issue by mengwong** [legalese-io/legalese-io.github.io#103]
see if Eddy is willing to act as an unpaid advisor to the startup, with the primary deliverable of nudging the academic NRF/NTU/NUS/SMU collaboration to life.

https://www.linkedin.com/in/eddysmlee

**Comment by mengwong** [comment]
had call. is interested. may invest.

**Comment by chiahli** [comment]
added to #potential investor list.

**Comment by chiahli** [comment]
he would be willing to help out in this area, provided the fund invests in us. Then we would be under his portfolio. Otherwise, he can't justify time spent with a company that's not the fund's portfolio.
