### ISSUE TITLE
Start outline for this ISIF.asia grant for 50k

### ISSUE THREAD

**Issue by virgil** [legalese-io/legalese-io.github.io#106]
http://isif.asia/Grants_TechnicalInnovation

I offer to contribute to this, but I request that Meng outline roughly what we want to say for each prompt.  The ideal output would be a slide of powerpoint-like bullets for each prompt that I can then weave into 1-2 paragraphs.

**Comment by mengwong** [comment]
maybe we should aim for the 30k since we are talking about prototyping the v2 rather than scaling the v1. https://docs.google.com/document/d/1cQzLnYxZFsmTEiVsmKclx13JCB92Wc1MnIWSTUN-7ZU/edit#

**Comment by mengwong** [comment]
application has been submitted: https://drive.google.com/drive/folders/0B-lTLNYJdzgKMkJSZXFRWHBaalk
