### ISSUE TITLE
consolidate all issues into one repository

### ISSUE THREAD

**Issue by mengwong** [legalese-io/legalese-io.github.io#114]
for all repositories except legalese-github-io and legalese-confidential,

move all nonconfidential issues into legalese-github-io

move all confidential issues into legalese-confidential repository.

i don't think there is a clever way of doing this – you just have to copy and paste a bunch.

related to #6.

**Comment by waitwtfff** [comment]
We should also ensure all issues are correctly labelled so that complete information is visible when filtering by labels. (e.g. #73 should be labelled 'google-apps'
