### ISSUE TITLE
create idea of spreadsheet-global config

### ISSUE THREAD

**Issue by mengwong** [legalese-io/legalese-io.github.io#116]
it's annoying to have to set the same "Add To Folder" config option in each tab of a spreadsheet.

make it so that if a tab INCLUDEs an Entities sheet, the CONFIGURATION section from Entities applies to the including sheet.

merge the including sheet's CONFIGURATION sections so that the including sheet has priority.

or maybe priority can be simply determined by the ordering – if the INCLUDE line comes above the primary sheet's CONFIGURATION line then primary sheet's configuration should just overwrite.

**Comment by waitwtfff** [comment]
IMO giving priority to the including sheet's config, irrespective of ordering, makes more sense.
