### ISSUE TITLE
Prepare for and meet with Floodgate's Arjun Chopra 

### ISSUE THREAD

**Issue by wabisabiyo** [legalese-io/legalese-io.github.io#129]
Meeting will be happening during our US trip (18 - 24 May)

WMW's instructions:
in preparation for meetings in the valley could i suggest @alexis please 
1.  download all of http://floodgate.com/arjunchopra.html's patents and
2.  also prepare a dossier summary of his work at his previous companies, particularly Vox?

if you could park them into a CRM subfolder on google drive i will be able to read the patents there also.

**Comment by wabisabiyo** [comment]
CRM folder created. Patents are hyperlinked in summary.

**Comment by mengwong** [comment]
i have added a few links about CTE's investments.
