### ISSUE TITLE
try to move templates to HTTPS to reduce at least one MITM attack vector

### ISSUE THREAD

**Issue by jobchong** [legalese-io/legalese-io.github.io#134]
_From @mengwong on September 28, 2015 13:47_

the execution of arbitrary code in the template creates the possibility of privilege escalation.

stop using mengwong.com. use github pages.

_Copied from original issue: legalese-io/legalese-google-app#7_

**Comment by mengwong** [comment]
or maybe use readme.io?

**Comment by mengwong** [comment]
have updated demo master / available templates with Base URL: https://raw.githubusercontent.com/legalese/legalese.github.io/master/templates/
