### ISSUE TITLE
register us on crunchbase

### ISSUE THREAD

**Issue by mengwong** [legalese-io/legalese-io.github.io#152]

**Comment by wabisabiyo** [comment]
need twitter to signup. will wait for twitter registration to go through (authenticated with phone and alternative handle to be chosen)

**Comment by byte** [comment]
I suggest creating a Twitter handle for legalese (say legalesecom), following it (gaining more followers), then asking twitter to transfer @legalese to us when we have traction. 

Worth reading: https://support.twitter.com/articles/15362 (which says we need a trademark)

**Comment by virgil** [comment]
https://www.crunchbase.com/organization/legalese

It's unclear to me who is a "founder".  Obviously Meng and Alexis.  It is unclear to me whether there are others.  FWIW, I think having my name as a co-founder is marginally useful.
