### ISSUE TITLE
Perceived Legitimacy Readiness - Minimum Viable Branding 

### ISSUE THREAD

**Issue by wabisabiyo** [legalese-io/legalese-io.github.io#158]
http://aleberrycreative.com/swag/perceived-legitimacy/#PitchTwo
**Due 14 Jun 2016**

Priorities:
a) Website - @jobchong @virgil @cbas 
b) Logo - @alexis @mengwong 
c) Business Cards (with logo) - @alexis @mengwong 
~~d). email address@legalese.com~~

Due to the limited time we have, I have pre-assigned you guys. If you can't do it, please let me know ASAP.

**Comment by jobchong** [comment]
I accept. Current version of website is using Bootstrap on GitHub Pages. Over the next week I will shift it to EC2 with Node and Express for signup forms. Note that this static site is branding only and only tangentially related to v2.

**Comment by virgil** [comment]
For business cards I recommend:
- http://mymetalbusinesscard.com
- http://plasmadesign.co.uk/

I can get you 10% discount from MyMetalBusinessCard.

**Comment by virgil** [comment]
- I accept #158a.
- I also just commissioned a logo for #158b.

**Comment by wabisabiyo** [comment]
@virgil what do you mean _commissioned_ a logo? if this requires money from legalese, the protocols were not followed through with so it's not kosher.

i have gotten a working free logo from someone i met at the hostel (see pr branding channel) which i will throw in the pool for consideration.

**Comment by virgil** [comment]
Paying for it myself.  Because I'm a nice chap.

**Comment by wabisabiyo** [comment]
Minimum viable branding for v2.1 fundraising:

see 10-slide pitchdeck for full details.
- [x]  logo
- [x]  slogan (software is eating law is a internal mission statement, not external statement)
- [x] namecards & tshirts
