### ISSUE TITLE
Perceived Legitimacy Readiness - Understanding the audience (investors)

### ISSUE THREAD

**Issue by wabisabiyo** [legalese-io/legalese-io.github.io#162]
SUGGESTED TODO:
DUE: before meetings are begun. 
1. Dossier for each of the investors we are going to approach (if too many, maybe focus on a few) 
2. Update SG investor list and tune in on gossip
3. Everyone going to do pitches will _have_ to read these dossiers before hand

**Comment by chiahli** [comment]
Not dossiers. 
I prefer to have investors information consolidated in one place and that will be the investors sheet that i'm currently updating.
Related to issue #163

**Comment by chiahli** [comment]
Sorted the current active investors into groups we plan to hit according to our strategy.
1.  First round angels 
2.  Second round angels
3.  the seed funds later on in the year + possibly the early-stage series A funds for dancing cards.
Related to issue #163
meng, is there anyone you want to take out from the sorted list?

**Comment by wabisabiyo** [comment]
@chiahli when i said dossier i had the arjun dossier we prepared in mind. https://drive.google.com/drive/u/0/folders/0BxUwY-mTI-hrdFN5SXdKcVlmV3M

**Comment by chiahli** [comment]
cool. i have included linkedin profiles.
angels + seed + early-stage good to go. 
i will work on series A/B next after we raised angel round 1. Unless you have a preference for me to do that earlier?

**Comment by mengwong** [comment]
the features i am most interested in are:
1. does the investor have experience founding a successful startup?
2. does the investor have experience founding a failed startup?
3. does the investor have a career primarily in finance or banking?
4. does the investor have a degree in computer science?
5. does the investor have at least two years of experience as a working programmer?
6. does the investor have any qualifications in law?
7. does the investor have operating experience as an executive in a high-tech company?

**Comment by chiahli** [comment]
wouldn't you know that by reading their linkedin profiles next to their names?
