### ISSUE TITLE
Complete shift of legalese.io content into readme.io

### ISSUE THREAD

**Issue by jobchong** [legalese-io/legalese-io.github.io#167]
Includes all the links and completion of tutorials for v1, and template hosting (tentative).

**Comment by virgil** [comment]
The content could be more polished.  But I believe all of the content is there.
- https://legalese.readme.io/v1.0/page/prior-art-and-alternatives
- https://legalese.readme.io/docs/angel-investment
- https://legalese.readme.io/docs/three-founders-incorporate-a-company
- https://legalese.readme.io/docs/tutorial-2-hello-world

It remains a little unclear to me how to best lay out the landing page.  It largely depends on how much we want to talk about things related to v2.

**Comment by mengwong** [comment]
i think the last thing to be cleaned up is moving the wall of text off the landing page, and adding some simple links that serve to CTA the different audiences.

**Comment by mengwong** [comment]
the principle is the same as what Paco Underhill described in Why We Buy as the "landing strip" – give users who are frenetically clicking an opportunity to click once more on their way in before they stop.

http://www.informedesign.org/_news/may_v02-p.pdf

**Comment by virgil** [comment]
Finished.
