### ISSUE TITLE
Creation of PhantomJS front end to make up for absence of ACRA API by 23 June

### ISSUE THREAD

**Issue by wabisabiyo** [legalese-io/legalese-io.github.io#171]
**Due:** 23 June 2016

Background

alexis [2:55 PM]  
so... colin meng and i had a discussion yesterday about UK being a better ground to start this. one because all the API documentation is ready, the information is free, and there are more startups and omney in the UK.

conversely, singapore's api documentation should have been ready 1 year ago (it still isn't, and is unlikely to be ready in the next 1 year), they intend to charge people for pull requests, and singapore has less money and startups.

[2:55]  
so thinking about the v2 ui and ux, it becomes increasingly clear that if we are to servce singapore startups WITHOUT ACRA API INTEGRATION, then we would either write scripts to do the incorporation for them, have to pay to be registered as a corp sec firm and keep up accounts for that matter, or pay for a human backend

mengwong [2:56 PM]  
given that companies house is so far ahead of ACRA in terms of API, i can see three possibilities.
1. forget about supporting SG companies and go straight for the UK market.
2. hire a human to gateway queries against the ACRA web interface
3. write an API layer using something like PhantomJS

alexis [2:56 PM]  
option 3 would also require acra registration as a QI (which i can do tonight) and registration as a business doing that. more licence expenditure and paperwork

[2:57]  
i am leaning towards 1 or 2. feels like corp sec on retainer for 2 might be cheap enough. but it's a dumb human backend. that doesn't quite help our eventual product

[2:58]  
or at least will help our product development in the same way (but lesser degree) as (1) would.

new messages
mengwong [3:03 PM]  
my preference is to spend a week seeing if we can build a PhantomJS front end to make up for the absence of an official ACRA API. (edited)

alexis [3:04 PM]  
and if that fails, we go straight to (1)?

mengwong [3:04 PM]  
i think so.

**Comment by mengwong** [comment]
i have posted https://groups.google.com/forum/#!topic/hackerspacesg/4_99lVGkYU4

**Comment by mengwong** [comment]
well, good effort was put into this – i think we have learned that the acra site is so hostile to casper/phantom that it's not worth the effort.

instead we will put energy into #187.

@jobchong, can you please log an estimate of # of hours you spent on this effort, somewhere in this thread, following the format seen in my comment to #170
