### ISSUE TITLE
update readme.io - blog especially

### ISSUE THREAD

**Issue by wabisabiyo** [legalese-io/legalese-io.github.io#174]
mengwong [4:10 PM]  
alexis: before our website goes live, can you please update the blog to be correct?

[4:11]  
the roadmap versioning in the box at the bottom should say v1 is concierge MVP, and v2 is user-friendly and fully automated

[4:11]  
v3 onwards will move toward the DSL

[4:11]  
if we are going to do a feature comparison matrix we should include a larger number of the other players.

[4:12]  
https://legalese.readme.io/blog/

[4:13]  
if it is too much work to do this, you could just delete that article, because it looks more like a placeholder / test entry

alexis [4:13 PM]  
okay will file an issue on this.

new messages
mengwong [4:13 PM]  
we will need to get all the pages on the new site cleaned up before we cut over.

[4:13]  
we should also get the existing blog (which has one post, lol) copied over to the new blog.

**Comment by virgil** [comment]
done.
