### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by byte** [legalese-io/legalese-io.github.io#177]
At the moment we have no idea who is visiting our site. I suggest we track this via Google Analytics (free, easy to setup, works well with static site pages). This will help when legalese.com is ready too as we can track user funnel progress and so forth.

**Comment by virgil** [comment]
Already being done under code: UA-63573011-4

If a different code is desired just paste it.

**Comment by byte** [comment]
@virgil - Will you update the site? Its currently not in any of the HTML (for www.legalese.io). I do notice it is at legalese.readme.io which is great!

**Comment by virgil** [comment]
have no control over legalese.io site.  However it seems we'll be moving to the readme.io site in near future.

**Comment by mengwong** [comment]
you can send a pull request or commit directly! the site's source code is in the repo.
