### ISSUE TITLE
look into Spring grants and Spring seeds

### ISSUE THREAD

**Issue by chiahli** [legalese-io/legalese-io.github.io#182]

**Comment by chiahli** [comment]
For SPRING SEEDS investment: we must have identified a third-party investor whether individual or corporate who's prepared to put in at least $75,000 each.

**Comment by chiahli** [comment]
For Spring TECS grant, sent out second draft to slack for internal review

**Comment by chiahli** [comment]
https://docs.google.com/document/d/1ga7PRHyOT-j2me2VKnaokIN0btQZfJl9bKiz75nEsSA/edit#

**Comment by wabisabiyo** [comment]
TECS grant submitted
