### ISSUE TITLE
create template for name cards

### ISSUE THREAD

**Issue by mengwong** [legalese-io/legalese-io.github.io#184]
create a legalese template that produces PDFs for name cards on A4, 90x54mm, suitable for submission to a printer.

**Comment by virgil** [comment]
If we are doing this in metal I can do it.

**Comment by mengwong** [comment]
doing it in metal would be so diesel. or so metal. but it would probably give the wrong idea about our spending patterns.

**Comment by mengwong** [comment]
maybe after we get Series A we can do metal business cards. that could be a little present to ourselves.

**Comment by virgil** [comment]
Plastic also good. http://www.plasmadesign.co.uk/plastic-business-cards/

I request a single metal card for us after series seed.  We need a good hook!

Oooh they also good wood.

http://www.plasmadesign.co.uk/wood-business-cards

**Comment by chiahli** [comment]
why not do it as a sticker?

**Comment by mengwong** [comment]
okay, we now have a tab in our Legalese spreadsheet https://docs.google.com/spreadsheets/d/1zPwx-0S6AwAyYtxtE0X64TkEXQywz99m56xZZWOv8cE/edit#gid=212450702 which will generate business cards

output folder
https://drive.google.com/drive/u/0/folders/0BxOaYa8pqqSwUHlNV3N0QkRNUjA
