### ISSUE TITLE
Re-consider the legalese mascot

### ISSUE THREAD

**Issue by virgil** [legalese-io/legalese-io.github.io#194]
**Background**: Peter Thiel writes:

> Disruption has recently transmogrified into a self-congratulatory buzzword for anything posing as trendy and new. This seemingly trivial fad matters because it dis-torts an entrepreneur's self-understanding in an inherently competitive way. The concept was coined to describe threats to incumbent companies, so startups' obsession with disruption means they see themselves through older firms' eyes. If you think of yourself as an insurgent battling dark forces, it's easy to become unduly fixated on the obstacles in your path. But if you truly want to make something new, the act of creation is far more important than the old industries that might not like what you create. Indeed, if your company can be summed up by its opposition to already existing firms, it can't be completely new and it's probably not going to become a monopoly.
> 
> Disruption also attracts attention: disruptors are people who look for trouble and find it. Disruptive kids get sent to the principal's office. Disruptive companies often pick fights they can't win. Think of Napster: the name itself meant trouble. What kinds of things can one "nap"? Music . . . Kids . . . and perhaps not much else. Shawn Fanning and Sean Parker, Napster's then-teenage founders, credibly threatened to disrupt the powerful music recording industry in 1999. The next year, they made the cover of Time magazine. A year and a half after that, they ended up in bankruptcy court.
> 
> PayPal could be seen as disruptive, but we didn't try to directly challenge any large competitor. It's true that we took some business away from Visa when we popularized internet payments: you might use PayPal to buy something online instead of using your Visa card to buy it in a store. But since we expanded the market for payments overall, we gave Visa far more business than we took. The overall dynamic was net positive, unlike Napster's negative-sum struggle with the U.S. recording industry. As you craft a plan to expand to adjacent markets, don't disrupt: avoid competition as much as possible.

**Claim:** Choosing the octopus (though I love and respect them so!) as Legalese's mascot because, "Octopodes are smart and [sometimes eat sharks (laywers)](https://www.youtube.com/watch?v=_HNZePQosxU)" falls prey to the same tendency Thiel cites. I propose our mascot instead symbolize something the customer cares about---removing bugs. I googled for photogenic animals that eat lots of bugs (insectivores). Here are the good ones: 

---
- Hedgehog [pics](https://www.google.com.sg/search?q=Hedgehog&safe=off&source=lnms&tbm=isch) [plushies](https://www.google.com.sg/search?safe=off&site=&tbm=isch&source=hp&q=Hedgehog+stuffed+animal) [beanie](https://www.google.com.sg/search?q=Hedgehog+%22beanie+baby%22&safe=off&source=lnms&tbm=isch)
- Echidna [pics](https://www.google.com.sg/search?q=Echidna&safe=off&source=lnms&tbm=isch) [plushies](https://www.google.com.sg/search?safe=off&site=&tbm=isch&source=hp&q=Echidna+stuffed+animal) [beanie](https://www.google.com.sg/search?q=Echidna+%22beanie+baby%22&safe=off&source=lnms&tbm=isch)
- Pangolin [pics](https://www.google.com.sg/search?q=Pangolin&safe=off&source=lnms&tbm=isch) [plushies](https://www.google.com.sg/search?safe=off&site=&tbm=isch&source=hp&q=Pangolin+stuffed+animal) [beanie](https://www.google.com.sg/search?q=Pangolin+%22beanie+baby%22&safe=off&source=lnms&tbm=isch)
- Anteater [pics](https://www.google.com.sg/search?q=Anteater&safe=off&source=lnms&tbm=isch) [plushies](https://www.google.com.sg/search?safe=off&site=&tbm=isch&source=hp&q=Anteater+stuffed+animal) [beanie](https://www.google.com.sg/search?q=Anteater+%22beanie+baby%22&safe=off&source=lnms&tbm=isch)
- Chameleon [pics](https://www.google.com.sg/search?q=Chameleon&safe=off&source=lnms&tbm=isch) [plushies](https://www.google.com.sg/search?safe=off&site=&tbm=isch&source=hp&q=Chameleon+stuffed+animal) [beanie](https://www.google.com.sg/search?q=Chameleon+%22beanie+baby%22&safe=off&source=lnms&tbm=isch)
- Sloth bear [pics](https://www.google.com.sg/search?q=Sloth bear&safe=off&source=lnms&tbm=isch) [plushies](https://www.google.com.sg/search?safe=off&site=&tbm=isch&source=hp&q=Sloth bear+stuffed+animal) [beanie](https://www.google.com.sg/search?q=Sloth bear+%22beanie+baby%22&safe=off&source=lnms&tbm=isch)
- Tenrec [pics](https://www.google.com.sg/search?q=Tenrec&safe=off&source=lnms&tbm=isch) [plushies](https://www.google.com.sg/search?safe=off&site=&tbm=isch&source=hp&q=Tenrec+stuffed+animal) [beanie](https://www.google.com.sg/search?q=Tenrec+%22beanie+baby%22&safe=off&source=lnms&tbm=isch)
- Aardvark [pics](https://www.google.com.sg/search?q=Aardvark&safe=off&source=lnms&tbm=isch) [plushies](https://www.google.com.sg/search?safe=off&site=&tbm=isch&source=hp&q=Aardvark+stuffed+animal) [beanie](https://www.google.com.sg/search?q=Aardvark+%22beanie+baby%22&safe=off&source=lnms&tbm=isch)
- Armadillo [pics](https://www.google.com.sg/search?q=Armadillo&safe=off&source=lnms&tbm=isch) [plushies](https://www.google.com.sg/search?safe=off&site=&tbm=isch&source=hp&q=Armadillo+stuffed+animal) [beanie](https://www.google.com.sg/search?q=Armadillo+%22beanie+baby%22&safe=off&source=lnms&tbm=isch)
- Aardwolf [pics](https://www.google.com.sg/search?q=Aardwolf&safe=off&source=lnms&tbm=isch) [plushies](https://www.google.com.sg/search?safe=off&site=&tbm=isch&source=hp&q=Aardwolf+stuffed+animal) [beanie](https://www.google.com.sg/search?q=Aardwolf+%22beanie+baby%22&safe=off&source=lnms&tbm=isch)
- Swallow [pics](https://www.google.com.sg/search?q=Swallow&safe=off&source=lnms&tbm=isch) [plushies](https://www.google.com.sg/search?safe=off&site=&tbm=isch&source=hp&q=Swallow+stuffed+animal) [beanie](https://www.google.com.sg/search?q=Swallow+%22beanie+baby%22&safe=off&source=lnms&tbm=isch)
- Numbat [pics](https://www.google.com.sg/search?q=Numbat&safe=off&source=lnms&tbm=isch) [plushies](https://www.google.com.sg/search?safe=off&site=&tbm=isch&source=hp&q=Numbat+stuffed+animal) [beanie](https://www.google.com.sg/search?q=Numbat+%22beanie+baby%22&safe=off&source=lnms&tbm=isch)
- Common shrew [pics](https://www.google.com.sg/search?q=Common shrew&safe=off&source=lnms&tbm=isch) [plushies](https://www.google.com.sg/search?safe=off&site=&tbm=isch&source=hp&q=Common shrew+stuffed+animal) [beanie](https://www.google.com.sg/search?q=Common shrew+%22beanie+baby%22&safe=off&source=lnms&tbm=isch)

**Comment by virgil** [comment]
I think one can't go wrong with the hedgehog, echidna, pangolin, anteater, chameleon, or perhaps even sloth bear.

**Comment by mengwong** [comment]
yeah, we did try out the hedgehog for a while … learnings from that: the hedgehog beanie baby sheds fur a lot.

**Comment by virgil** [comment]
there exist other hedgehogs, as well as other animals.

My suggestion is merely to have an insectivore mascot.

**Comment by virgil** [comment]
One of my colleagues suggests the Pangolin because:
- Pangolin is vaguely mechanical-looking, and our product is mechanical.
- Pangolin is an asian animal, and we're an asian startup.  Pangolin is even native to Singapore!

Also:
- Hedgehog is okay because it has a protective covering and cute.
- Octopus is too squishy and edible to convey the image we want.

**Comment by virgil** [comment]
@mengwong: This is the best I got for plushy pangolins.
- https://www.amazon.com/Disney-Jungle-Book-Pangolin-Plush/dp/B016Q2SJAI
- Find someone who ordered this? https://www.alibaba.com/product-detail/D108-Wild-Animals-Plush-Stuffed-Pangolin_60358796401.html?spm=a2700.7724857.0.0.WWkpWR
- https://www.amazon.com/Schleich-North-America-Pangolin-Figure/dp/B01AJNM6O0/ref=pd_sim_sbs_21_3?ie=UTF8&dpID=41dNp3wLjpL&dpSrc=sims&preST=_AC_UL160_SR160%2C160_&psc=1&refRID=H5RZDV2FV4FTNNTYM4AN
- https://www.amazon.com/Safari-Incredible-Creatures-Pangolin/dp/B001Q6X5HM/ref=sr_1_2?ie=UTF8&qid=1469955888&sr=8-2&keywords=pangolin+plush
- https://www.amazon.com/Mojo-Fun-387174-Indian-Pangolin/dp/B00NK8NSKI/ref=sr_1_14?ie=UTF8&qid=1469955888&sr=8-14&keywords=pangolin+plush
- Misc pangolins: https://www.etsy.com/sg-en/listing/257135508/nolan-pangolin-scaly-anteater-plush?ref=market

**Comment by virgil** [comment]
It seems that we have agreed on Clause the **Pangolin**.  Glory be!
