### ISSUE TITLE
show a part of the sheet ID in the cover page

### ISSUE THREAD

**Issue by mengwong** [legalese-io/legalese-io.github.io#214]
we once had a hard time figuring out which sheet generated certain PDFs. We read the PDFs but we didn't immediately see which sheet they came from.

proposed solution: in templates that use `coverpage.indt`, somewhere near the date and time on the cover page, record the last 8 digits of the sheet ID. That will give us more of a clue in future.

you may need to update more than one xml template – grep the XMLs for `CoverBottom` and `Output Date` to see how the cover pages are constructed.

along the way you may feel the need to refactor the bottom of the cover page into something that can be `inc_`luded.

but start with `inc_cover_legalese.xml` and `inc_cover_jfdi.xml` and see how far that gets you. then look at the other templates whose names start with `inc_cover`.

ROLES REQUIRED
v1 developer

**Comment by waitwtfff** [comment]
@chiahli @wabisabiyo In the latest templates, the cover page of each pdf should now contain an 8-character identifier at the bottom. Please report here any templates where this does not happen.

**Comment by waitwtfff** [comment]
This issue can be reopened if any templates are found for which the cover page is missing the sheet ID.
