### ISSUE TITLE
collective@legalese.com Results in mailer-daemon error

### ISSUE THREAD

**Issue by Gauntlet173** [legalese-io/legalese-io.github.io#215]
Attempted to request an invite, got the following:
...
We're writing to let you know that the group you tried to contact (active-team) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:
...

**Comment by jobchong** [comment]
Hi @Gauntlet173, I've reviewed the permissions on active-team and you should be able to see the group and its posts now.
