### ISSUE TITLE
PDF generated from full-time-contract-3-months template has spacing and formatting issues 

### ISSUE THREAD

**Issue by wabisabiyo** [legalese-io/legalese-io.github.io#239]
https://legalese.slack.com/archives/github/p1482078679000020

Thought it was the white spaces (which I know shouldn't be factored in) but can't see why the formatting shows up weirdly. Maybe it's something I'm not getting with Indesign formats. 

What the main headers and sub-headers are should be apparent from the XML, but it's not showing up cleanly on the PDF. 

Want to hopefully resolve this by today so we can generate the contract properly

**Comment by mengwong** [comment]
it would be nice to get support for partytype being "director[0],director[1]" which means we want the first two directors. how do we do that? see templates.js circa line 200

**Comment by wabisabiyo** [comment]
@mengwong: I need help. the  inc_enumerate signatures script should result in the signature block being executed by the parties (company and contractor). Currently it reads:
executed by...
contractor
[signature block]

directors
[signature block for dir 1]
[signature block for dir 2]

What I need for the contract, on the company end, is for it to say that it is signed by 2 directors _for the company_, rather than it simply listing the 2 directors as signatories without reference to the company (reason being:  the directors are not parties to the contract, they are only the people executing the contract on behalf of the company).

**Comment by jobchong** [comment]
5c5026c727a94d7ffa3fc3ff24e8c19ac90a4fc5 adds functionality for custom headers without pluralisation. Documented at https://github.com/legalese/legalese-google-app#how-to-customize-inc_enumerate_signatures
