### ISSUE TITLE
Formatting and media work for legalese.github.io

### ISSUE THREAD

**Issue by jobchong** [legalese-io/legalese-io.github.io#252]
- [x] Embed images and media into pages which are missing them, e.g. most of `/announcements`
- [x] Format and include notices, callouts and warnings in `/docs`
- [x] Minor CSS tweaks
- [x] Include some missing tables
- [x] Port `/announcements` and its sidebar

**Comment by jobchong** [comment]
6daeeac411562aabadb8820e33ec7068625ffe8a for `/announcements`
ef18526e2db56d8c4bead80bd6b8abab144ce10b for `/announcements` sidebar
e3465f9666fd6d24e015bad360382587336ad2f6 for some images
1f107255c09d1be561c9e71952b18f155e1e6d2f for tables

**Comment by waitwtfff** [comment]
More work:
- [x]  Add missing line breaks at various places
- [x]  Add/fix CSS (for code styling, border below page title, image captions, etc.)
- [x]  Missing subheadings for documentation under "The Company"

**Comment by jobchong** [comment]
After the good work done by @anuj and also related work by @DustinWehr in #254, I'm closing this issue.
