### ISSUE TITLE
Fix broken links in legalese.com

### ISSUE THREAD

**Issue by jobchong** [legalese-io/legalese-io.github.io#254]
Some of the baseurls for the links were not updated by @jobchong in the migration from readme to github pages.

@DustinWehr has done some work to fix his carelessness, at https://github.com/legalese/legalese.github.io/commit/0405b5a65c2801272295d62a6c790e45590ab694 and https://github.com/legalese/legalese.github.io/commit/ff42a1a9ce477a94c60a022c7f2be5f8ed8ed4cc

**Comment by DustinWehr** [comment]
i think the readme.io links are fixed. there were only a few. i'll try to put the other broken links found by brokenlinkcheck.com in here, as it takes a while to run.

**Comment by DustinWehr** [comment]
Bad  http://legalese.com/v1.0/page/legalspace.world/service/visa
On  http://legalese.com/v1.0/page/present

Bad  http://legalese.com/docs
On  http://legalese.com/v1.0/page/future

Bad  http://legalese.com/docs/page:help-my-startup-needs-legal-agreements
On  http://legalese.com/docs/getting-started

Bad  http://legalese.com/docs/page:prior-art-and-alternatives
On  http://legalese.com/docs/getting-started

Bad  http://legalese.com/v1.0/blog/a-food-eating-contract
On  http://legalese.com/docs/hello-future-lexdevs

Bad  http://legalese.com/docs/doc:tutorial-2-hello-world
On  http://legalese.com/docs/three-founders-incorporate-a-company

Bad  http://legalese.com/docs/doc:tutorial-3-send-for-signature
On  http://legalese.com/docs/3-a-real-nondisclosure-agreement

Bad  http://legalese.com/v1.0/page/www.nytimes.com/2008/11/23/magazine/23wwln-medium-t.html
On  http://legalese.com/v1.0/page/media-kit.html

Bad  https://legalese.com/pages/future
On  https://legalese.com/

Bad  https://legalese.com/pages/contact
On  https://legalese.com/

Bad  https://legalese.com/v1.0/page/legalspace.world/service/visa
On  https://legalese.com/v1.0/page/present

Bad  https://legalese.com/docs/page:help-my-startup-needs-legal-agreements
On  https://legalese.com/docs/getting-started

Bad  https://legalese.com/docs/page:prior-art-and-alternatives
On  https://legalese.com/docs/getting-started

Bad  https://legalese.com/v1.0/page/www.nytimes.com/2008/11/23/magazine/23wwln-medium-t.html
On  https://legalese.com/v1.0/page/media-kit

Bad  https://legalese.com/v1.0/blog/a-food-eating-contract
On  https://legalese.com/docs/hello-future-lexdevs

Bad  https://legalese.com/docs/doc:tutorial-2-hello-world
On  https://legalese.com/docs/three-founders-incorporate-a-company

Bad  https://legalese.com/docs/doc:tutorial-3-send-for-signature
On  https://legalese.com/docs/3-a-real-nondisclosure-agreement

Bad  http://www.tbrnet.org/blog/2014/08/01/legal-update-bilingual-contracts/
On  http://legalese.com/

Bad  https://prestonbyrne.com/2016/06/20/failing-fast-vs-failing-unnecessarily/
On  http://legalese.com/v1.0/page/past

Bad  http://szabo.best.vwh.net/smart_contracts_idea.html
On  http://legalese.com/v1.0/page/past

Bad  http://contractcode.meteor.com
On  http://legalese.com/v1.0/page/past

Bad  http://stashcrypto.com/smart-contracts-info
On  http://legalese.com/v1.0/page/past

Bad  http://www.diku.dk/~paba/pubs/entries/bahr15icfp.html
On  http://legalese.com/v1.0/page/past

Bad  http://www.askthevc.com/wp/archives/tag/cap-table
On  http://legalese.com/v1.0/page/present

Bad  http://www.radiantlaw.com/how-we-work/document-automation/
On  http://legalese.com/v1.0/page/present

Bad  https://caserails.com
On  http://legalese.com/v1.0/page/present

Bad  https://www.ramendocs.com
On  http://legalese.com/v1.0/page/present

Bad  http://www.legify.com
On  http://legalese.com/v1.0/page/present

Bad  https://www.intelllex.com/users/sign_up
On  http://legalese.com/v1.0/page/present

Bad  http://szabo.best.vwh.net/contractlanguage.html
On  http://legalese.com/v1.0/page/present

Bad  http://susa.io
On  http://legalese.com/v1.0/page/present

Bad  http://www.elock.com/solutions.html
On  http://legalese.com/v1.0/page/present

Bad  https://artificiallawyer.com)
On  http://legalese.com/v1.0/page/present

Bad  href="http://www.abajournal.com/magazine/article/latest_legal_victory_has_legalzoom_poised_for_growth
On  http://legalese.com/v1.0/page/present

Bad  https://en.wikipedia.org/wiki/Read%25E2%2580%2593eval%25E2%2580%2593print_loop
On  http://legalese.com/docs/test-input

Bad  http://www.iftf.org/our-work/people-technology/the-human-internet/forecasting-the-internet/
On  http://legalese.com/announcements/wellwishers-oct-2016

Bad  https://github.com/legalese/legalese.com/blob/master/blog/20160710-haskell.org
On  http://legalese.com/announcements/wellwishers-aug-2016

Bad  https://www.bvca.co.uk/ResearchPublications/Publications/StandardIndustryDocuments/Modeldocumentsforearlystageinvestments.aspx
On  http://legalese.com/v1.0/page/present

Bad  https://www.digitalasset.com/press/introducing-daml.html
On  http://legalese.com/v1.0/page/present"

**Comment by DustinWehr** [comment]
- [x] Bad  http://legalese.com/pages/future
On  http://legalese.com/

- [x] Bad  http://legalese.com/pages/contact
On  http://legalese.com/

- [x] Bad  http://legalese.com/v1.0/page/legalspace.world/service/visa
On  http://legalese.com/v1.0/page/present

- [x] Bad  http://legalese.com/docs
On  http://legalese.com/v1.0/page/future

- [x] Bad  http://legalese.com/docs/page:help-my-startup-needs-legal-agreements
On  http://legalese.com/docs/getting-started

- [x] Bad  http://legalese.com/docs/page:prior-art-and-alternatives
On  http://legalese.com/docs/getting-started

- [x] Bad  http://legalese.com/v1.0/blog/a-food-eating-contract
On  http://legalese.com/docs/hello-future-lexdevs

- [x] Bad  http://legalese.com/docs/doc:tutorial-2-hello-world
On  http://legalese.com/docs/three-founders-incorporate-a-company

- [x] Bad  http://legalese.com/docs/doc:tutorial-3-send-for-signature
On  http://legalese.com/docs/3-a-real-nondisclosure-agreement

- [x] Bad  http://legalese.com/v1.0/page/www.nytimes.com/2008/11/23/magazine/23wwln-medium-t.html
On  http://legalese.com/v1.0/page/media-kit.html

- [x] Bad  https://legalese.com/pages/future
On  https://legalese.com/

- [x] Bad  https://legalese.com/pages/contact
On  https://legalese.com/

- [x] Bad  https://legalese.com/v1.0/page/legalspace.world/service/visa
On  https://legalese.com/v1.0/page/present

- [x] Bad  https://legalese.com/docs/page:help-my-startup-needs-legal-agreements
On  https://legalese.com/docs/getting-started

- [x] Bad  https://legalese.com/docs/page:prior-art-and-alternatives
On  https://legalese.com/docs/getting-started

- [x] Bad  https://legalese.com/v1.0/page/www.nytimes.com/2008/11/23/magazine/23wwln-medium-t.html
On  https://legalese.com/v1.0/page/media-kit

- [x] Bad  https://legalese.com/v1.0/blog/a-food-eating-contract
On  https://legalese.com/docs/hello-future-lexdevs

- [x] Bad  https://legalese.com/docs/doc:tutorial-2-hello-world
On  https://legalese.com/docs/three-founders-incorporate-a-company

- [x] Bad  https://legalese.com/docs/doc:tutorial-3-send-for-signature
On  https://legalese.com/docs/3-a-real-nondisclosure-agreement

- [x] Bad  http://www.tbrnet.org/blog/2014/08/01/legal-update-bilingual-contracts/
On  http://legalese.com/ **Replaced**

- [x] Bad  https://prestonbyrne.com/2016/06/20/failing-fast-vs-failing-unnecessarily/
On  http://legalese.com/v1.0/page/past **Replaced**

- [x] Bad  http://szabo.best.vwh.net/smart_contracts_idea.html
On  http://legalese.com/v1.0/page/past **Replaced**

- [x] Bad  http://contractcode.meteor.com
On  http://legalese.com/v1.0/page/past **Replaced**

- [x] Bad  http://stashcrypto.com/smart-contracts-info
On  http://legalese.com/v1.0/page/past **Replaced**

- [x] Bad  http://www.diku.dk/~paba/pubs/entries/bahr15icfp.html
On  http://legalese.com/v1.0/page/past **Replaced**

- [x] Bad  http://www.askthevc.com/wp/archives/tag/cap-table
On  http://legalese.com/v1.0/page/present **Replaced**

- [x] Bad  http://www.radiantlaw.com/how-we-work/document-automation/
On  http://legalese.com/v1.0/page/present **Replaced**

- [x] Bad  https://caserails.com
On  http://legalese.com/v1.0/page/present **Defunct, but link found and replaced**

- [x] Bad  https://www.ramendocs.com
On  http://legalese.com/v1.0/page/present **Defunct and removed**

- [x] Bad  http://www.legify.com
On  http://legalese.com/v1.0/page/present **Defunct and removed**

- [x] Bad  https://www.intelllex.com/users/sign_up
On  http://legalese.com/v1.0/page/present **Replaced**

- [x] Bad  http://szabo.best.vwh.net/contractlanguage.html
On  http://legalese.com/v1.0/page/present **Replaced**

- [x] Bad  http://susa.io
On  http://legalese.com/v1.0/page/present **Defunct and removed**

- [x] Bad  http://www.elock.com/solutions.html
On  http://legalese.com/v1.0/page/present **Hacked website, removed**

- [x] Bad  https://artificiallawyer.com)
On  http://legalese.com/v1.0/page/present

- [x] Bad  href="http://www.abajournal.com/magazine/article/latest_legal_victory_has_legalzoom_poised_for_growth
On  http://legalese.com/v1.0/page/present

- [x] Bad  https://legalese.readme.io/discuss
On  http://legalese.com/v1.0/page/contact

- [x] Bad  https://legalese.readme.io/v1.0/docs/1-hello-world
On  http://legalese.com/docs/general-info

- [x] Bad  https://en.wikipedia.org/wiki/Read%25E2%2580%2593eval%25E2%2580%2593print_loop
On  http://legalese.com/docs/test-input

- [x] Bad  http://www.iftf.org/our-work/people-technology/the-human-internet/forecasting-the-internet/ 
On  http://legalese.com/announcements/wellwishers-oct-2016 **Replaced**

- [x] Bad  https://github.com/legalese/legalese.com/blob/master/blog/20160710-haskell.org
On  http://legalese.com/announcements/wellwishers-aug-2016

- [x] Bad  https://legalese.readme.io/docs/angel-investment
On  http://legalese.com/announcements/july-9th-presentation

- [x] Bad  https://www.bvca.co.uk/ResearchPublications/Publications/StandardIndustryDocuments/Modeldocumentsforearlystageinvestments.aspx
On  http://legalese.com/v1.0/page/present **Replaced**

- [x] Bad  https://www.digitalasset.com/press/introducing-daml.html
On  http://legalese.com/v1.0/page/present **Replaced**
