### ISSUE TITLE
Archival with Slack

### ISSUE THREAD

**Issue by jobchong** [legalese-io/legalese-io.github.io#5]
Figure out a way to archive all links and files from Slack into Drive or an updated archive.html.

**Comment by jobchong** [comment]
Slack-to-RSS is live, but iffy with files and furled links. Uses Slack API token to access Slack directly.
Downloaded archives in JSON are clear, but manual, snapshot instead of live. One .json for each day.

**Comment by mengwong** [comment]
maybe we should use scrollback.io which has public archives by default.

**Comment by mengwong** [comment]
hm, maybe scrollback doesn't have archives the way i'd like them to.

**Comment by jobchong** [comment]
Alright, I have not arrived at a solution to this problem in either direction. http://stackoverflow.com/questions/32907767/can-i-have-a-recursive-javascript-function-inside-a-getjson-function for the .json approach.
