### ISSUE TITLE
turn the stumply ventures material into anonymized, generic templates

### ISSUE THREAD

**Issue by mengwong** [legalese-io/legalese-io.github.io#76]
https://drive.google.com/drive/folders/0B-lTLNYJdzgKelgxTlptdXdqVUE contains a bunch of confidential templates. convert these into typical Legalese XML templates suitable for filling from the usual Seed Round spreadsheet. those templates could live under templates/cubcapital.

**Comment by chiahli** [comment]
this may be related to issue #70

**Comment by chiahli** [comment]
i also see cub's templates xml - does this means that this issue and #70 are resolved?

**Comment by mengwong** [comment]
no, we haven't really converted their templates fully – they're not ready for use. but i think this issue is going quiet so we can mark it abandoned.
